<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__User__CLASSMETADATA__' => 0,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\User',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UserRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'username' => $o[2],
                    'name' => $o[3],
                    'email' => $o[4],
                    'enable' => $o[5],
                    'birthdate' => $o[6],
                    'address' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'username' => 'username',
                    'name' => 'name',
                    'email' => 'email',
                    'enable' => 'enable',
                    'birthdate' => 'birthdate',
                    'address' => 'address',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'username' => 'username',
                    'name' => 'name',
                    'email' => 'email',
                    'enable' => 'enable',
                    'birthdate' => 'birthdate',
                    'address' => 'address',
                ],
            ],
            'table' => [
                [
                    'name' => 'ex01_users',
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\User',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
                'boolean',
                'datetime',
                'text',
            ],
            'fieldName' => [
                1 => 'id',
                'username',
                'name',
                'email',
                'enable',
                'birthdate',
                'address',
            ],
            'columnName' => [
                1 => 'id',
                'username',
                'name',
                'email',
                'enable',
                'birthdate',
                'address',
            ],
            'length' => [
                2 => 64,
                64,
                128,
            ],
            'unique' => [
                2 => true,
                4 => true,
            ],
            'options' => [
                5 => [
                    'default' => false,
                ],
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
