<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVlUsiWx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVlUsiWx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVlUsiWx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVlUsiWx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerVlUsiWx\App_KernelProdContainer([
    'container.build_hash' => 'VlUsiWx',
    'container.build_id' => '5422d96e',
    'container.build_time' => 1762610465,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVlUsiWx');
