<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'ex01_index' => [[], ['_controller' => 'App\\Controller\\Ex01Controller::index'], [], [['text', '/ex01']], [], [], []],
    'ex01_create_table' => [[], ['_controller' => 'App\\Controller\\Ex01Controller::createTable'], [], [['text', '/ex01/create_table']], [], [], []],
];
